# Generated by Django 5.2.12 on 2026-03-12 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persona",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sarah", "Dr. Sarah — Registered Dietitian"),
                            ("maya", "Coach Maya — Performance Specialist"),
                            ("lena", "Dr. Lena — Pregnancy & Postpartum RD"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "biological_sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other / Prefer not to say"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lose_weight", "Lose Weight"),
                            ("gain_muscle", "Gain Muscle"),
                            ("eat_healthier", "Eat Healthier"),
                            ("manage_condition", "Manage a Health Condition"),
                            ("pregnancy", "Pregnancy / Postpartum Support"),
                            ("energy", "More Energy"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sedentary", "Sedentary (little or no exercise)"),
                            ("lightly_active", "Lightly Active (1–3 days/week)"),
                            ("moderately_active", "Moderately Active (3–5 days/week)"),
                            ("very_active", "Very Active (6–7 days/week)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("medical_conditions", models.JSONField(blank=True, default=list)),
                (
                    "medical_conditions_other",
                    models.CharField(blank=True, max_length=255),
                ),
                ("food_allergies", models.JSONField(blank=True, default=list)),
                ("food_allergies_other", models.CharField(blank=True, max_length=255)),
                ("medications", models.TextField(blank=True)),
                ("supplements", models.TextField(blank=True)),
                ("onboarding_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
