# Generated by Django 5.2.12 on 2026-03-12 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0002_userprofile_cooking_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodRecallDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Day 1"), (2, "Day 2"), (3, "Day 3")]
                    ),
                ),
                ("breakfast", models.TextField(blank=True)),
                ("lunch", models.TextField(blank=True)),
                ("dinner", models.TextField(blank=True)),
                ("morning_snack", models.TextField(blank=True)),
                ("afternoon_snack", models.TextField(blank=True)),
                ("evening_snack", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_recall_days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
                "unique_together": {("user", "day_number")},
            },
        ),
    ]
