# Generated by Django 5.2.12 on 2026-03-13 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0006_chatmessage_dailymessagecount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                ("adherence_score", models.PositiveSmallIntegerField(default=0)),
                ("meals_followed", models.PositiveSmallIntegerField(default=0)),
                ("total_meals", models.PositiveSmallIntegerField(default=0)),
                ("headline", models.TextField(blank=True)),
                ("wins", models.JSONField(default=list)),
                ("nutrient_summary", models.JSONField(default=list)),
                ("focus_next_week", models.JSONField(default=dict)),
                ("persona_closing", models.TextField(blank=True)),
                ("raw_response", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start"],
                "unique_together": {("user", "week_start")},
            },
        ),
    ]
