# Generated by Django 5.2.12 on 2026-03-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0007_weeklyreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "demo_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Enable demo/investor preview mode — all premium features visible for every user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="demo_premium",
            field=models.BooleanField(
                default=False, help_text="Grant premium preview for this user"
            ),
        ),
    ]
